### ISSUE TITLE
Incorrect behavior when loading a local bed file into IGV

### ISSUE THREAD

**Issue by kairukuma** [igvteam/spacewalk#256]
Hi, I ran into an issue when loading a local bed file onto IGV where the color-coded annotations specified in the bed file aren't displaying correctly. It seems that one chromosome is highlighted in gray and the rest of the chromatin is shaded blue. I'm using this shared session:

https://aidenlab.org/spacewalk/?spacewalkSessionURL=blob:dVTbbpwwEP0XPwNrgzGwUtWHpI2aXhI1VV6qKjLGsG69NjFms5so_96xN2kjkYBk4XNmztxsHtDsNFqjjffjtF6t7u7uss7ZsbX7TNjtalo1rRi66Q.bqbpVGJBRS2lu.lnrTJlO7mWXCdO17zv9DqMEaSvmCa0fkNg4EIaVADpIY7dKXHnuPFqTf8AH06F1ThscHvKYIO.4kJ_lAVyDmhp2l9xIDY5eAmaskQA7CZHdlT_oAB536RS2qVNtaw3YjMHvWk2qVVr5Q0jp09l1VAsFq66Twex8VkJCuQviVE2eGyG_8nHBnVjjufAfnbydpRGHpQ2UMkCF1rzM4L_AkTux2rqQmDv2JK4trMHb2dl0lxpk35CIBmMweKmDswY3NS6anJSsZnlFo_BrcPsaDKEF30rHv6hh45UZvqshSG.l5x33PHzvpJsUNHlNsxJGdhjDFC7a31L446zB3YeMnsDiNPP2_OriW2iLPdqBzDwrmD5iLe5xm5OUEYZTWvYs5ZiItCh4RbHsctKHI_QU5hJijyCgdvIk5gmUgQ.grGuV5_pGPOOaH8A6dnXLvVN7tP5JEvz0kiRlGW6g9rquaooLRnOZkiqSrzPROSsKgmtGyroqc0oJTUhWkaLCDBNWUlxSkuR5mRUlrirWMFZQ6G5CfiWotzvIhmQAkNjtpoEYMIp7a7cxTyN5HCItSU0aTHFdM0pABJwDE_DsBVEF0XjjCE4Qj62JQr3S2zM.D9CYojxuL_p.ksBimMJoJ.XjDB_QPgRcFIXgtC0LQ_dwXxfFhYvL3SDjWP0ben4pmFcF4CCZ4qwEU1rQCo5hxaqyfgwncXnPnq_lj42T08bq8P8o2eNf&sessionURL=blob:pZNRa9swFIX_ShB92MCVLSddZsMYbA_Zw9ggpXRjjHLtyLaYJbmSbDcN.e.7kpJthb1sNeQESzqfrnWPDmTixgqtSElyyjLKSEJsp.drkEPPP4HklpQN9JYnxPCGG65qTsoDETu0dC0r0KBwGb59GCWoxYvN9n23XKd.7iVONmAd3Gw_.uXODbZMU9FOtOWKD.AcN4pq06b4rnGz1PL7YA1CgxkhQu34w7MgqAJB9d7pCtTuP1je.g6t1D04JEEvwD7F2CUFCY9awWxprWXgIoueWb9qugtu6qDyNXVGS21xxWez4waBOMKSBWoedBl0FfQq6Kug66CvgxZBWRb_optFO4t.FgEsElhEsMhgEcIiJY.U_FRDpHwJ.pUcE9LresRYEFayy3xVJFmW4c9Hxxmof.DUtwNx.8GHAo9vDJlJiI5fd1lk2ZoVRX61Wq.yomDH5HCO0JY3aFhssBfWZ0cbCQ7HMXq.Pz4J59zdtadFo.n_uQeqrgTudc3vqdXG8dBU2j7.PWrPY1JX.eRNwopK9MLtb3ELPeNBMLxr4zDgYnvb6Z5vAu6P.yb1BFX_e.R0giwLj6.10U9LneeZ.kKo6iVVoqOtnnyUefoWky3fXFz4LsXWgFLagfO3__j9.BM-

I'm using this bed file for testing:
http://genome.compbio.cs.cmu.edu:8008/~kxiong/data/sniper/annotations/hg19/GM12878_track_hg19.bed

If I'm not using this correctly, could you provide some advice for properly loading the bed file?
Any help is greatly appreciated. Thanks!

- Kyle

**Comment by turner** [comment]
@kairukuma I'll take a look.

**Comment by jrobinso** [comment]
Hi, I'm looking at the file in IGV (igv.org/app) and this is what I see at whole genome view.   I don't know what to expect, does this look correct?   @turner will look into the Spacewalk issue,  I'm just trying to separate isssues

<img width="1617" alt="Screen Shot 2023-02-08 at 3 45 08 PM" src="https://user-images.githubusercontent.com/933148/217677488-eb05d2ac-22b0-471c-b7d2-9aab98d28e6d.png">

**Comment by kairukuma** [comment]
Hi, that looks correct for the whole genome view. Thanks for looking into this!

**Comment by jrobinso** [comment]
OK, this is what I see in Spacewalk, which also looks  reasonable.  Could you tell us at what locus you noticed the issue?

<img width="1353" alt="Screen Shot 2023-02-08 at 8 25 52 PM" src="https://user-images.githubusercontent.com/933148/217717844-f7804983-7cef-4381-81fb-b425731c4564.png">

**Comment by kairukuma** [comment]
If you toggle the check next to the custom track, you should see the issue I'm referencing. My understanding is that the annotations should be reflected in the 3D model as well, but correct me if I'm mistaken. Thank you.

**Comment by jrobinso** [comment]
@kairukuma Ahh, that's a question for @turner .   I was just verifying the IGV part,  sorry for the misunderstanding (on my part).

**Comment by jrobinso** [comment]
BTW I think you're doing everything correctly,  its just a minor SW bug.  It seems to be picking up the default track color (blue) rather than the color of individual features.   The grey you see is areas where there are no features.

**Comment by turner** [comment]
@kairukuma regarding the mapping of colors from igv track to 3D trace, this is what I see in the latest build of Spacewalk:
![Screen Shot 2023-02-09 at 9 04 01 AM](https://user-images.githubusercontent.com/87169/217834509-9a3a6529-2fce-48c6-829e-b0b3f944c852.png)

There is an issue with the actual colors assigned to the 3D trace as well as the distribution of the colors along the trace. Those are bugs I will look into.


The build is located here 
Netlify hosted https://spacewalk-site.netlify.app/

or here:

Erez Aiden Lab: http://3dg.io/spacewalk/

**Comment by turner** [comment]
@kairukuma I have a fix for the color mapping:
![Screen Shot 2023-02-09 at 10 44 43 AM](https://user-images.githubusercontent.com/87169/217863165-da2e47f5-9e1f-4dc5-a3c0-e877491ecad0.png)

I'll let you know when it is live in the production build

**Comment by kairukuma** [comment]
@turner @jrobinso Thanks for looking into this! The newest update looks great. Looking forward to the production build.

**Comment by turner** [comment]
@kairukuma the production app is now updated:
https://spacewalk-site.netlify.app/

Give it a try and let me know.

**Comment by turner** [comment]
I'll assume this issues is resolved.
