### ISSUE TITLE
Gray localizations hiding highlighted localizations

### ISSUE THREAD

**Issue by gnir** [igvteam/spacewalk#259]
Hi @turner,

I have a point cloud sw file and I'm looking at the localizations in my traces. When I'm trying to look at one segment of the trace the other localizations are shown in gray. However, these gray localizations are 'hiding' my highlighted localizations. I think, you should have the option to not show the not-selected localizations or have them transparent.

Thank you,
Guy

**Comment by turner** [comment]
@gnir here is an idea I came up with to prevent the un-highlighted points from obscuring the highlighted points. What do you think?

https://user-images.githubusercontent.com/87169/219702674-1ceb845f-1e27-49fe-893a-08848f208be4.mov


Here is a test share url to try it out:
https://tinyurl.com/2kn5nwtu

**Comment by gnir** [comment]
Hi @turner,

Liked it a lot. Would it be possible to select several segments together? For instance, by holding ctrl or shift?

Apologies but I might be slower to respond until Tuesday.
Guy

**Comment by turner** [comment]
@gnir I merged these changes with the production app:
https://spacewalk-site.netlify.app/

I'll close this issue and open one specifically to address the segment selection idea

**Comment by gnir** [comment]
Thank you!
Guy

**Comment by gnir** [comment]
@turner - I am not able to select multiple targets.
Also - the track won't color the trace (like it does for simulation and balls-and-sticks). And, the distance map is not working.

Thank you,
Guy

**Comment by turner** [comment]
@gnir I created this issue as a record that I need to work on it. I haven't started on it yet.

**Comment by gnir** [comment]
@turner - oh, I see. I misunderstood you.
Guy

**Comment by turner** [comment]
> @turner - oh, I see. I misunderstood you. Guy

For pointcloud rendering, distance map - and contact map - is not implemented. 
I also do not map igv track feature colors to pointclouds. This would not be very usable as the number of genomic locations in the track - and thus locations for a color - are extremely sparse for point cloud and thus would not look particularly convincing. Just a small set of color splotches.

**Comment by gnir** [comment]
> For pointcloud rendering, distance map - and contact map - is not implemented.

Why? You find the mean(XYZ) location for each step.

'Just a small set of color splotches.'
Maybe it makes sense to generate a density map (or another type of a volumetric visualization) for each target and add the IGV tracks on these?

**Comment by turner** [comment]
> > For pointcloud rendering, distance map - and contact map - is not implemented.
> 
> Why? You find the mean(XYZ) location for each step.
> 
> 'Just a small set of color splotches.' Maybe it makes sense to generate a density map (or another type of a volumetric visualization) for each target and add the IGV tracks on these?

The fundamental issue with mapping color from track to trace - any flavor of trace (ball/stick, ribbon, pointcloud) - has to do with sampling. Specifically, an igv track may have around a thousand on screen features. A given ball/stick model may have a few dozen balls. Each ball is a single genomic location at which I sample the track (feature) for color. So, the ball/stick or ribbon or point cloud will **severally** under sample the track color distribution creating an aliased "point sampled" version of the nice continuous track color distribution.

**Comment by gnir** [comment]
Still, that's what people do. For instance, you can color the entirety of the density map with the feature that is dominant over that region. Does that make sense?
Check out supplemental figure 10 from [this paper](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007872) as an example.
Guy

**Comment by turner** [comment]
Ok, got it. I won't worry about the undersampling issue. I'll create:
1) an issue to add live density/distance maps to pointcloud
2) an issue to map track feature color to pointclouds

Thanks for all the super helpful input Guy

**Comment by gnir** [comment]
It's funny how you are thanking me... I'm planning on using it 😁

**Comment by turner** [comment]
@gnir I'm getting the pointcloud distance/contact map and track feature mapping happening first. I'll circle back to discuss density maps

**Comment by gnir** [comment]
Thank you :)
Guy
