### ISSUE TITLE
Walking along the IGV tracks doesn't work in the shared links

### ISSUE THREAD

**Issue by gnir** [igvteam/spacewalk#262]
Hello @turner and @jrobinso,

I've noticed that if I load a track bed file from a URL, I can move my mouse along that track and the corresponding area will show on the spacewalk trace. But, when I share this view with my collaborators, they can't do so with the link I shared with them
[Here is an example](https://tinyurl.com/2e67ac4d)
Guy

**Comment by jrobinso** [comment]
@turner Also, clicking on the track selection boxes in  IGV does not affect the color of the spacewalk structure view.  It looks like the IGV track and SW are decoupled.

**Comment by turner** [comment]
I'll take a look.

**Comment by turner** [comment]
@gnir @jrobinso here is a shareable url of a possible fix:
https://tinyurl.com/2esuqntc

Still very laggy due to the high number of renderable objects (~1.5M). Jim the igv panel menus should work better. I am now using a branch of igvjs and discarded the local hacked copy I had been using.

The test app is here:
https://deploy-preview-263--spacewalk-site.netlify.app/

**Comment by gnir** [comment]
Hi @turner,

I am still unable to walk along the bed track and see the corresponding region in the trace.
Thank you,
Guy

**Comment by turner** [comment]
@gnir hmmm. Try this and let me know if you  can "walk" in the igvjs panel:
https://tinyurl.com/2dut374c

This is a smaller point cloud file. I want to try and isolate the issue.

**Comment by gnir** [comment]
@turner - no, I can't.
Guy

**Comment by turner** [comment]
@gnir, what if you launch the test app https://deploy-preview-263--spacewalk-site.netlify.app/ (rather then using a share url) and open the file. Do you see the same result as when you use the share url I provided?

**Comment by turner** [comment]
@gnir I think I have an idea about what's happing. I'm working on a fix now.

**Comment by gnir** [comment]
@turner, great! I can tell you that when I loaded the files from URL it worked for me. But when I shared with others, it didn't work for them.
Guy

**Comment by turner** [comment]
@gnir ok I think it got it. Try this share url:
https://tinyurl.com/2ov6lzcz

**Comment by gnir** [comment]
@turner - working, thank you!

**Comment by turner** [comment]
Great. Go ahead and use the production app now.
https://spacewalk-site.netlify.app/

This test app - and the shareable url based on it - will go away in a or two.

**Comment by turner** [comment]
@gnir I've reopened this issue with news of a significant speed up.

Check it out and let me know what you think:
https://tinyurl.com/2nhsrg2h

This update is now live in the production app:
https://spacewalk-site.netlify.app/

**Comment by gnir** [comment]
Tested and it's soooooo much faster!
Guy
